const { Prisma, PrismaClient, User } = require('@prisma/client');
const prisma = new PrismaClient();

const users = [
  {
    email: 'user1@example.com',
    name: 'Emma Johnson',
    thumbnail: "https://example.com/'thumbnail'1.jpg",
    weight: 65,
    favAddresses: ['123 Pine St', '456 Cedar Ave'],
    homeAddress: '789 Oak Ln',
    location_lat: 40.7128,
    location_lng: -74.006,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T09:00:00Z',
    lastLoginDate: '2023-05-24T09:00:00Z',
    firstRideCity: 'New York',
    firstRideCountry: 'United States',
    monthlyMiles: 100,
    ridesThisWeek: 5,
    monthlyDownvotedReports: 0,
    totalRoutes: 10,
    totalReports: 3,
    totalPosts: 8,
    totalMiles: 300,
    totalLikesReceived: 50,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/2281/2281179.png',
  },
  {
    email: 'user2@example.com',
    name: 'Liam Smith',
    thumbnail: "https://example.com/'thumbnail'2.jpg",
    weight: 70,
    favAddresses: ['234 Pine St', '567 Cedar Ave'],
    homeAddress: '890 Oak Ln',
    location_lat: 37.7749,
    location_lng: -122.4194,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T09:15:00Z',
    lastLoginDate: '2023-05-24T09:15:00Z',
    firstRideCity: 'San Francisco',
    firstRideCountry: 'United States',
    monthlyMiles: 90,
    ridesThisWeek: 4,
    monthlyDownvotedReports: 1,
    totalRoutes: 12,
    totalReports: 7,
    totalPosts: 10,
    totalMiles: 250,
    totalLikesReceived: 60,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/5716/5716364.png',
  },
  {
    email: 'user3@example.com',
    name: 'Oliver Brown',
    thumbnail: "https://example.com/'thumbnail'3.jpg",
    weight: 73,
    favAddresses: ['345 Pine St', '678 Cedar Ave'],
    homeAddress: '901 Oak Ln',
    location_lat: 51.5074,
    location_lng: -0.1278,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T09:30:00Z',
    lastLoginDate: '2023-05-24T09:30:00Z',
    firstRideCity: 'London',
    firstRideCountry: 'United Kingdom',
    monthlyMiles: 120,
    ridesThisWeek: 8,
    monthlyDownvotedReports: 0,
    totalRoutes: 15,
    totalReports: 2,
    totalPosts: 6,
    totalMiles: 400,
    totalLikesReceived: 40,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/10552/10552271.png',
  },
  {
    email: 'user4@example.com',
    name: 'Isabella Davis',
    thumbnail: "https://example.com/'thumbnail'4.jpg",
    weight: 68,
    favAddresses: ['456 Pine St', '789 Cedar Ave'],
    homeAddress: '012 Oak Ln',
    location_lat: 45.4215,
    location_lng: -75.6972,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T09:45:00Z',
    lastLoginDate: '2023-05-24T09:45:00Z',
    firstRideCity: 'Ottawa',
    firstRideCountry: 'Canada',
    monthlyMiles: 80,
    ridesThisWeek: 6,
    monthlyDownvotedReports: 0,
    totalRoutes: 20,
    totalReports: 5,
    totalPosts: 4,
    totalMiles: 500,
    totalLikesReceived: 30,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/3732/3732831.png',
  },
  {
    email: 'user5@example.com',
    name: 'Sophia Wilson',
    thumbnail: "https://example.com/'thumbnail'5.jpg",
    weight: 62,
    favAddresses: ['567 Pine St', '890 Cedar Ave'],
    homeAddress: '123 Oak Ln',
    location_lat: 34.0522,
    location_lng: -118.2437,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T10:00:00Z',
    lastLoginDate: '2023-05-24T10:00:00Z',
    firstRideCity: 'Los Angeles',
    firstRideCountry: 'United States',
    monthlyMiles: 70,
    ridesThisWeek: 3,
    monthlyDownvotedReports: 0,
    totalRoutes: 13,
    totalReports: 4,
    totalPosts: 2,
    totalMiles: 200,
    totalLikesReceived: 10,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/1187/1187563.png',
  },
  {
    email: 'user6@example.com',
    name: 'Noah Jones',
    thumbnail: "https://example.com/'thumbnail'6.jpg",
    weight: 75,
    favAddresses: ['678 Pine St', '901 Cedar Ave'],
    homeAddress: '234 Oak Ln',
    location_lat: 37.3382,
    location_lng: -121.8863,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T10:15:00Z',
    lastLoginDate: '2023-05-24T10:15:00Z',
    firstRideCity: 'San Jose',
    firstRideCountry: 'United States',
    monthlyMiles: 110,
    ridesThisWeek: 7,
    monthlyDownvotedReports: 0,
    totalRoutes: 18,
    totalReports: 1,
    totalPosts: 9,
    totalMiles: 600,
    totalLikesReceived: 20,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/3843/3843036.png',
  },
  {
    email: 'user7@example.com',
    name: 'Ava Martinez',
    thumbnail: "https://example.com/'thumbnail'7.jpg",
    weight: 64,
    favAddresses: ['789 Pine St', '012 Cedar Ave'],
    homeAddress: '345 Oak Ln',
    location_lat: 43.6532,
    location_lng: -79.3832,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T10:30:00Z',
    lastLoginDate: '2023-05-24T10:30:00Z',
    firstRideCity: 'Toronto',
    firstRideCountry: 'Canada',
    monthlyMiles: 60,
    ridesThisWeek: 2,
    monthlyDownvotedReports: 0,
    totalRoutes: 11,
    totalReports: 6,
    totalPosts: 5,
    totalMiles: 150,
    totalLikesReceived: 80,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/4841/4841913.png',
  },
  {
    email: 'user8@example.com',
    name: 'Charlotte Taylor',
    thumbnail: "https://example.com/'thumbnail'8.jpg",
    weight: 69,
    favAddresses: ['890 Pine St', '123 Cedar Ave'],
    homeAddress: '456 Oak Ln',
    location_lat: 41.8781,
    location_lng: -87.6298,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T10:45:00Z',
    lastLoginDate: '2023-05-24T10:45:00Z',
    firstRideCity: 'Chicago',
    firstRideCountry: 'United States',
    monthlyMiles: 130,
    ridesThisWeek: 9,
    monthlyDownvotedReports: 0,
    totalRoutes: 14,
    totalReports: 2,
    totalPosts: 7,
    totalMiles: 450,
    totalLikesReceived: 70,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/9100/9100364.png',
  },
  {
    email: 'user9@example.com',
    name: 'Mia Anderson',
    thumbnail: "https://example.com/'thumbnail'9.jpg",
    weight: 67,
    favAddresses: ['012 Pine St', '234 Cedar Ave'],
    homeAddress: '567 Oak Ln',
    location_lat: 25.7617,
    location_lng: -80.1918,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T11:00:00Z',
    lastLoginDate: '2023-05-24T11:00:00Z',
    firstRideCity: 'Miami',
    firstRideCountry: 'United States',
    monthlyMiles: 75,
    ridesThisWeek: 3,
    monthlyDownvotedReports: 0,
    totalRoutes: 17,
    totalReports: 3,
    totalPosts: 3,
    totalMiles: 350,
    totalLikesReceived: 90,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/1910/1910054.png',
  },
  {
    email: 'user10@example.com',
    name: 'Liam Johnson',
    thumbnail: "https://example.com/'thumbnail'10.jpg",
    weight: 71,
    favAddresses: ['123 Pine St', '345 Cedar Ave'],
    homeAddress: '678 Oak Ln',
    location_lat: 51.0447,
    location_lng: -114.0719,
    recentRouteId: null,
    theme: true,
    joinDate: '2023-05-24T11:15:00Z',
    lastLoginDate: '2023-05-24T11:15:00Z',
    firstRideCity: 'Calgary',
    firstRideCountry: 'Canada',
    monthlyMiles: 95,
    ridesThisWeek: 5,
    monthlyDownvotedReports: 0,
    totalRoutes: 16,
    totalReports: 4,
    totalPosts: 1,
    totalMiles: 550,
    totalLikesReceived: 40,
    selectedBadge: 'https://cdn-icons-png.flaticon.com/512/3284/3284649.png',
  },
];

const userSeeder = async () => {
  try {
    for (const user of users) {
      const existingUser = await prisma.user.findUnique({
        where: { email: user.email },
      });

      if (existingUser) {
        await prisma.user.update({
          where: { email: user.email },
          data: user,
        });
        console.log(`User ${user.email} already exists and has been updated`);
      } else {
        await prisma.user.create({ data: user });
        console.log(`User ${user.email} created`);
      }
    }

    console.log('User seeding completed');
  } catch (error) {
    console.error('Error seeding users:', error);
  } finally {
    await prisma.$disconnect();
  }
};

userSeeder();
